pimcore/data-hub

- src/GraphQL/Query/QueryType.php
> Removes debug code from QueryType

- src/Controller/ConfigController.php
My IDE was sad when these didn't exists. Making it happier :)
> Includes @throws in ConfigController method docs

- doc/graphl/Operators.md
- src/GraphQL/OperatorConfigGenerator/ThumbnailHtml.php
- src/GraphQL/Query/Operator/ThumbnailHtml.php
- src/PimcoreDataHubBundle.php
- src/Resources/config/services.yml
- src/Resources/public/js/operator/ThumbnailHtml.js
Fixes: #13 by adding a separate transformer operator that returns the full html string.
> Adds the ability to return a full <img> tag

- src/Resources/translations/admin.en.yml
Sorry. I *knew* I forgot something!
> Thumbnail HTML: Adds missing admin translation

- src/Controller/WebserviceController.php
No need for `die()` and also phpdocs
> Allows WebserviceController to return JsonResponse

- src/Controller/GraphQLExplorerController.php
* `now` -> `new` is the important part :)
* Better method docs with @params and @throws
* CamelCases clientName variable
* Removes unnecessary variable
> Fixes proper Exception throwing and some minor code cleanup

- doc/graphl/Queries.md
- src/GraphQL/QueryFieldConfigGenerator/Video.php
- src/GraphQL/Resolver/QueryType.php
- src/GraphQL/Resolver/Video.php
- src/GraphQL/Type/VideoType.php
- src/GraphQL/Type/VideoTypeDataType.php
- src/Resources/config/graphql.yml
> Videoquery

- src/Configuration.php
- src/GraphQL/Resolver/Base.php
Fixes `ErrorException ... array_keys() expects parameter 1 to be array, null given`
> Hardens Configuration against null values and fixes docs/return types

- doc/graphl/Queries.md
- src/GraphQL/QueryFieldConfigGenerator/CalculatedValue.php
- src/Resources/config/graphql.yml
> Support for Calculated Value datatype

- doc/graphl/Queries.md
- src/GraphQL/QueryFieldConfigGenerator/QuantityValue.php
- src/GraphQL/Resolver/QuantityValue.php
- src/GraphQL/Type/AssetInputType.php
- src/GraphQL/Type/QuantityValueType.php
- src/GraphQL/Type/QuantityValueUnitType.php
- src/Resources/config/graphql.yml
> Support for Quantity Value query

- src/Controller/WebserviceController.php
and throw more explicit error. performSecurityCheck() now returns void because the return value is never used anyway
> Updates webserviceController to strengthen security check

- doc/graphl/Mutations.md
- src/GraphQL/InputProcessor/Image.php
- src/GraphQL/MutationFieldConfigGenerator/Image.php
- src/GraphQL/Type/InputType/AbstractRelationInputType.php
- src/GraphQL/Type/InputType/ImageInputType.php
- src/Resources/config/graphql.yml
> Add support for image mutation

- src/GraphQL/Query/QueryType.php
> Clarifies totalCount schema description

- doc/graphl/Queries.md
- src/GraphQL/FieldcollectionDecriptor.php
- src/GraphQL/Mutation/MutationType.php
- src/GraphQL/QueryFieldConfigGenerator/Helper/Href.php
- src/GraphQL/QueryFieldConfigGenerator/Helper/Multihref.php
- src/GraphQL/QueryFieldConfigGenerator/Helper/MultihrefMetadata.php
- src/GraphQL/Service.php
- src/GraphQL/Type/AbstractRelationsType.php
- src/GraphQL/Type/FieldcollectionType.php
- src/GraphQL/Type/PimcoreObjectType.php
- src/Resources/config/graphql.yml
> Support for fieldcollection queries

- src/GraphQL/InputProcessor/ManyToOneRelation.php
- Resolves #88 
- Declares void return type
- Uses static closure (micro-optimisation)
- Single white-space at end of file
> Improves manyToOneRelation process() method

- src/GraphQL/Query/QueryType.php
- src/GraphQL/QueryFieldConfigGenerator/ImageGallery.php
> sortBy multiple columns

- doc/GraphQL.md
- doc/graphl/Queries.md
Should have added to previous PR
> Docs: Markdown style and schema change for sorting

- src/Controller/ConfigController.php
I was looking for something else and found this, I just assume it was an unnoticed bug
> Removes possibly errounous negation in $config

- src/Configuration.php
See src/Resources/public/js/configItem.js
> Fixes incorrect key for SQL Condition

- src/Command/GraphQL/RebuildDefinitionsCommand.php
- src/Configuration.php
- src/Configuration/Dao.php
- src/Controller/ConfigController.php
- src/EventListener/DataChangeListener.php
- src/PimcoreDataHubBundle.php
- src/Resources/config/eventlistener.yml
- src/Resources/config/services.yml
- src/Resources/public/js/configItem.js
- src/WorkspaceHelper.php
Beside of improving symfony standards, this will prevent exceptions like these (while executing tests for example):
> Add EventListener to dedicated EventListener Class

- src/GraphQL/Mutation/MutationType.php
> Correctly assign locale service when building data object mutations

- src/GraphQL/AssetType/AssetType.php
> Fix Assets fullpath(thumbnail:) and data(thumbnail:) 

- doc/graphl/AddCustomQueryDatatype.md
- doc/graphl/AddCustomQueryOperator.md
Fixed urls to javascript and classes and updated to current version and master branch
> Documentation fixes: Links to examples

- src/GraphQL/Mutation/MutationType.php
- src/GraphQL/Query/QueryType.php
> [Events] Pass info from pre-build events

- doc/graphl/querysamples/Sample_GetAsset.md
- src/GraphQL/AssetType/AssetType.php
Adds a new field "srcset" to AssetType (solves issue #169)
> Add mediaqueries to AssetType

- src/GraphQL/Helper.php
- src/GraphQL/Resolver/QueryType.php
> [Pimcore7] decouple condition builder from deprecated webservices

- src/GraphQL/DocumentType/PageSnippetType.php
- src/GraphQL/SharedType/KeyValueType.php
Ticket: #183
Query:
```graphql
{
getDocument (id: 2) {
... on document_page {
id,
rendered (
use_layout: false, 
options: [{key: "blub", value: "blub"}]
attributes: [{key: "blub", value: "blub"}]
query: [{key: "blub", value: "blub"}]
)
}
}
}
```
Result: 
```json
{
"data": {
"getDocument": {
"id": "2",
"rendered": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <title>Example</title>\n</head>\n\n<body>\n\n<style type=\"text/css\">\n    body {\n        padding:0;\n        margin: 0;\n        font-family: \"Lucida Sans Unicode\", Arial;\n        font-size: 14px;\n    }\n\n    #site {\n        margin: 0 auto;\n        width: 600px;\n        padding: 30px 0 0 0;\n        color:#65615E;\n    }\n\n    h1, h2, h3 {\n        font-size: 18px;\n        padding: 0 0 …
```
> Documents: Add Schema to pre-render Document for GraphQl Output with Parameters 

- src/GraphQL/DocumentType/AbstractDocumentType.php
- src/GraphQL/DocumentType/PageSnippetType.php
Add title and description fields on documents
> Add title and description fields on documents

- src/GraphQL/FieldHelper/AbstractFieldHelper.php
> Support for fragments

- src/GraphQL/Service.php
> [Asset] Localized Field Language Property not working

- README.md
I had issues during installation and think this aids for helping others with the same problem
> Added step to verify installation

- src/Controller/GraphQLExplorerController.php
> Disable Tags & Snippet Management in GraphiQL

- src/GraphQL/Mutation/MutationType.php
See issue #203 for further details. Hoping to have implemented the flag as proposed.
> Adding omitMandatoryCheck to create-mutation

- doc/graphl/Events.md
- src/Event/GraphQL/ListingEvents.php
- src/Event/GraphQL/Model/ListingEvent.php
- src/GraphQL/Helper.php
- src/GraphQL/Query/QueryType.php
- src/GraphQL/Resolver/QueryType.php
> implement new event before loading listing data

- src/Controller/ConfigController.php
- src/Controller/GraphQLExplorerController.php
- src/Resources/public/js/configItem.js
> [Admin] Explorer - Fix open in tab

- composer.json
- phpunit.xml.dist
- src/Configuration.php
- src/Controller/WebserviceController.php
- src/Resources/config/services.yml
- src/Service/CheckConsumerPermissionsService.php
- tests/Service/CheckConsumerPermissionsServiceTest.php
> Support sending apikey via headers in addition to sending it via query param

- src/GraphQL/Resolver/AssetType.php
> Fix Asset thumbnail resolutions returning same url for different resolutions

- doc/graphl/FieldcollectionMutations.md
- doc/graphl/Mutations.md
- src/GraphQL/DataObjectInputProcessor/Base.php
- src/GraphQL/DataObjectInputProcessor/BaseOperator.php
- src/GraphQL/DataObjectInputProcessor/Date.php
- src/GraphQL/DataObjectInputProcessor/ExternalImage.php
- src/GraphQL/DataObjectInputProcessor/Fieldcollections.php
- src/GraphQL/DataObjectInputProcessor/Geopoint.php
- src/GraphQL/DataObjectInputProcessor/IfEmptyOperator.php
- src/GraphQL/DataObjectInputProcessor/Image.php
- src/GraphQL/DataObjectInputProcessor/LocaleSwitcherOperator.php
- src/GraphQL/DataObjectInputProcessor/ManyToManyObjectRelation.php
- src/GraphQL/DataObjectInputProcessor/ManyToManyRelation.php
- src/GraphQL/DataObjectInputProcessor/ManyToOneRelation.php
- src/GraphQL/DataObjectMutationFieldConfigGenerator/Fieldcollections.php
- src/GraphQL/DataObjectType/AbstractRelationsType.php
- src/GraphQL/FieldHelper/DataObjectFieldHelper.php
- src/GraphQL/Mutation/MutationType.php
- src/GraphQL/Service.php
- src/Resources/config/graphql.yml
> Add support for fieldcollections mutations

- CONTRIBUTING.md
- src/Configuration.php
- src/Resources/public/js/configuration/graphql/configItem.js
> Optimize config dialog

- src/GraphQL/Service.php
Fixes pimcore/data-hub#316 by passing the requested language to the Block Getter in GraphQL Service.
Forgive me if this isn't state-of-the-art PHP, if not consider this a pointer into where the issue might originate. Been a while since I last did lots of PHP (back in the 5.x days!).
> Fixes pimcore/data-hub#316 localized blocks GraphQL

- src/GraphQL/Resolver/QueryType.php
Don't count, if i don't use it. :)
> Use resolver for performance / fix missing quote

- src/Event/GraphQL/Model/OutputCachePreLoadEvent.php
- src/Event/GraphQL/Model/OutputCachePreSaveEvent.php
> [PimcoreX] Fix Symfony\Component\EventDispatcher\Event deprecations #333

- src/GraphQL/FieldHelper/AssetFieldHelper.php
- src/GraphQL/Resolver/AssetType.php
> [PimcoreX] Fix getFileSystemPath deprecations

- src/GraphQL/DataObjectInputProcessor/Geopoint.php
- src/GraphQL/Resolver/Geobounds.php
- src/GraphQL/Resolver/Geopoint.php
> [PimcoreX] Fix \Pimcore\Model\DataObject\Data\Geopoint deprecations #335

- src/Resources/config/graphql.yml
> Unable to query on ReverseObjectRelation fields

- src/GraphQL/FieldHelper/AbstractFieldHelper.php
> Fix Image thumbnail transformer
