src/GraphQL/Query/QueryType.php, src/GraphQL/Resolver/QueryType.php
While the previous PR only added the field as a return value (which only ever returned `true`) this allows us to get the publication status like this to include both published and unpublished objects:
```
{
getProductListing(published: false) {
edges {
node {
id
name
sku
published
...
```
=> Follow-up to  #8 to include actual ability to include unpublished objects

src/GraphQL/Mutation/MutationType.php
Also: Will not attempt to sort if there is only one mutation, see #43
=> Prevents a fatal error when no mutations are configured

src/Configuration.php
The first time a new Configuration is saved, the `$securityConfig` value can be `null`, this prevents that PHP notice.
=> Avoid PHP Notice on first time a Configuration is saved

src/GraphQL/InputProcessor/Base.php, src/GraphQL/InputProcessor/IfEmptyOperator.php, src/GraphQL/MutationOperatorConfigGenerator/Base.php, src/GraphQL/Query/Operator/AbstractOperator.php, src/GraphQL/Query/Operator/Alias.php, src/GraphQL/Query/Operator/Concatenator.php, src/GraphQL/Query/Operator/DateFormatter.php, src/GraphQL/Query/Operator/ElementCounter.php, src/GraphQL/Query/Operator/Merge.php, src/GraphQL/Query/Operator/Substring.php, src/GraphQL/Query/Operator/Thumbnail.php, src/GraphQL/Query/Operator/ThumbnailHtml.php, src/GraphQL/Query/Operator/TranslateValue.php, src/GraphQL/Query/Operator/Trimmer.php, src/GraphQL/Resolver/Base.php, src/GraphQL/Type/MergeType.php, src/Resources/public/js/fieldConfigDialog.js, src/WorkspaceHelper.php
Resolves #59.
Also changes related verbiage while attempting to retain Pimcore 5 compatibility by checking for:
```php
$children = method_exists($this, 'getChildren') ? $this->getChildren() : $this->getChilds();
```
That should be easy enough to remove in a future update when Pimcore 5 support is dropped.
=> Renames 'childs' to 'children'

src/GraphQL/QueryFieldConfigGenerator/Hotspotimage.php, src/GraphQL/QueryFieldConfigGenerator/ImageGallery.php
Fix for **unknown type: hotspot** thrown in [GraphQL/Service.php](https://github.com/pimcore/data-hub/blob/master/src/GraphQL/Service.php#L449), introduced due to change in graphql.yml
=> Bugfix: Hotspotimage renamed broke imagegalleries

src/GraphQL/Resolver/QueryType.php
Even if the GQL would complain about using a string where an array of strings were used in the query the listing would accept it, this caused a slight mismatch when running automated queries.
=> Updates QueryType to align with array arguments

src/Configuration.php, src/Configuration/Dao.php, src/Controller/ConfigController.php, src/Installer.php, src/Resources/public/js/configItem.js
Resolves #97 
However, this PR does not yet touch the `"key" => "#5d..."` in datahub-configuration.php (because I don't understand it yet) but does a number of other things:
* Adds return types, implements class constant for reused string, normalises Exception class import according to comments, moves to shorthand ifs (`?:`) for configController.php
* Adds return types, normalises Exception throwing, adds access keywords, and method docs for Dao.php
* Adds return types, simplifies IsInstalled() logic, uses ConfigController constant for name in Installer.php
* Prevents SQL hint and API info from saving in datahub-configuration.php
=> Config improvements

src/GraphQL/DocumentResolver/PageSnippet.php
Orders the document elements by the order they have in blocks, that is the same order the elements/bricks are ordered in admin.
Closes #139.
=> Order document elements by the order they are in blocks

src/GraphQL/AssetType/AssetType.php
This PR:
- will return the full path for asset types beside images/videos like audio. Currently,`fullpath` returns `null` 
- refactors the `AssetType` class to prevent duplicate code
=> Fullpath for non Thumbnail Aware Assets

src/GraphQL/DocumentElementType/LinkDataType.php
Target is named windowTarget because Target is already in use.
=> Adding new missing fields to LinkDataType.

src/Controller/WebserviceController.php
While writing some functional tests for my client using Codeception I stumbled upon some behaviour in the `WebserviceController` which makes it almost impossible to write a functional test, without al kind of strange hacks, if even possible.
My setup is the following:
- enabled the `Pimcore\Tests\Helper\Pimcore` codeception module, which can act as an `InnerBrowser` and directly do requests to the Symfony kernel
- Wrote a `GraphQL` module which uses the `Pimcore` module to dispatch GraphQL requests.
The implementation described above expects the Symfony response and request objects to be used. This is good practice anyway as you are not expected to directly access superglobals or headers in a Symfony application as this could cause unwanted side effects.
I have refactored `php:://input` …
=> Use symfony requests and response objects

src/GraphQL/DataObjectType/ObjectFolderType.php
```graphql
{
getObjectFolder(id: 3) {
fullpath
properties(keys: ["test","obj"]) {
... on property_text {
name, text
},
... on property_object {
object {
... on object_test {
test
}
}
}
}
}
}
```
```json
{
"data": {
"getObjectFolder": {
"fullpath": "/testtest",
"properties": [
{
"object": {
"test": "test"
}
},
{
"name": "test",
"text": "test"
}
]
}
}
}
```
=> add object folder properties

src/GraphQL/DocumentElementType/RelationsType.php
While working with the latest version (`dev-master`) of this package to query a document via GraphQL, I noticed both `_tagType` and `_tagName` would always return `null` when accessing a Relations (plural) tag whereas these attributes would have the expected values for the Relation (singular) tag. This is the query in question:
```gql
query getDocument($path: String!) {
getDocument(path: $path) {
... on document_page {
fullpath
elements {
... on document_tagRelation {
_tagName # non-null in result
_tagType # non-null in result
}
... on document_tagRelations {
_tagName # null in result
_tagType # null in result
}
}
}
}
}
}
```
In the case of Relations, these attributes are set in `src/GraphQL/DocumentElementType/RelationsType.php` and it looks like this file was originally based on …
=> Document query: use correct tag for instanceof check to fix null attributes

src/Resources/public/js/workspace/abstract.js
Use-Case: Only show specific permissions
pimcore.plugin.pimcoreDataSyndicatorBundle.workspace.object = Class.create(pimcore.plugin.datahub.workspace.abstract, {
type: "object",
availableRights : ['read'],
rightCheckboxHidden : true,
rightCheckboxDisabled : true
});
=> Make workspace setting configurable

src/GraphQL/ClassificationstoreType/Group.php
Overriding the language parameter with "default" seems like a typo to me(?)
=> respect language parameter for classification store queries

src/Controller/WebserviceController.php, src/Event/GraphQL/Model/ExecutorEvent.php
this allows modification of the variable values (and therefore the whole query - if needed) in the preExecute event.
the change also introduces a backward compatible way to set the request property of the ExecutorEvent to an actual request object (like the event is created by it's constructor) and not only to a string
=> read query variables after preExecute event

src/GraphQL/ClassificationstoreType/Group.php
When the language is not indicated in a Classification Store query, the `defaultLanguage` (if present) should be taken into account before stating that the language should be set to `default`.
This modification will take into account the Locale of the GraphQL service. The Locale property contains the value of the `defaultLanguage` when this parameter is specified in the query.
=> Default language parameter in classification store queries

src/Controller/WebserviceController.php
fixes #304
The original request object's parameter bags somehow aren't populated (I guess that's why originally the variable values are parsed from the request body).
One may ask why after the event the variable values are read from the parameter bags (and not via request body parsing like before). The reason is that inside the event setting a single parameter (like variables) via request body would be cumbersome.
The solution for now is to provide the variable values from the original request body are provided as default/fallback while reading the variables from the parameter bags (so if the parameter bags are empty the originally parsed variable values are returned).
=> use already parsed variables as fallback

src/GraphQL/Mutation/MutationType.php
When using GraphQL API to create an image asset, the server replies with an HTTP 500 error and the following stacktrace:
**Request**
``` graphql
mutation createMyImage($path: String!, $filename: String!, $imageData: String!) {
createAsset(path: $path, filename: $filename, type: "image", input: {data: $imageData, filename: $filename}) {
success
message
assetData {
modificationDate
}   
}
}
```
**Variables**
``` json
{
"filename": "my-image.png",
"path": "/my-images",
"imageData": "/9j/4AAQSkZJRg..."
}
```
**Error**
``` php
Call to a member function resolveObjectGetter() on array 
in vendor/pimcore/data-hub/src/GraphQL/Mutation/MutationType.php (line 834)
"assetData" => [
'args' => ['defaultLanguage' => ['type' => Type::string()]],
'type' => $assetType,
'resolve' => static function ($value, …
```
=> Fix 'Call to a member function resolveObjectGetter() on array' when creating and image via GraphQL

src/Resources/public/js/workspace/abstract.js
This PR changes the UI behavior of adding new records to the workspace store. Instead of prepending new records this appends the newly created record. This makes it more intuitive for the user, which expects the record to be added at the bottom.
=> [Workspaces] Use add instead of insert to add new store record

src/GraphQL/AssetType/AssetInputType.php
Currently Datahub doesn't support adding/updating metadata in assets mutations, even though I can get the metadata in queries. By adding the 'Metadata' input parameter, the existing code is able to save/replace the metadata. To test it you can use the createAsset or the updateAsset mutations, for instance:
```graphql
mutation ($filename: String!, $path: String, $input: AssetInput) {
createAsset(filename: $filename, path: $path, type: "document", input: $input) {
success
message
assetData {
metadata {
name
type
data
}
}
}
}
{
"filename": "my-doc.pdf",
"path": "/telco",  
"input": {
"filename": "my-doc.pdf",
"metadata": [
{
"name": "my-metadata",
"type": "input",
"data": "my-value"
},
{
"name": "another-metadata",
"type": "input",
"data": "another-value"
}
],
data: "base 64 encoded data"
} …
```
=> Added support to set metadata on assets

doc/10_GraphQL/10_Events.md, doc/10_GraphQL/README.md, src/Controller/WebserviceController.php, src/DependencyInjection/Configuration.php, src/Event/GraphQL/Model/OutputCachePreLoadEvent.php, src/Event/GraphQL/Model/OutputCachePreSaveEvent.php, src/Event/GraphQL/OutputCacheEvents.php, src/Service/OutputCacheService.php, tests/Service/OutputCacheServiceTest.php
Draft for #273:
- config.yml file can be used to enable graphql output cache and set items lifetime. If not provided, defaults are: cache disabled, 30 seconds lifetime
- cache can be disabled for a single request (if debug mode is on) by setting query params to true (pimcore_nocache, pimcore_outputfilters_disabled)
- graphql output cache uses the default cache backend configured for pimcore (Doctrine, Redis,...)
=> Provide response cache
